#!/usr/bin/env python3
import click
import daemon
import lockfile
import logging
import logging.config
import os
from logging.handlers import TimedRotatingFileHandler

from aws_watchdog import aws_watchdog
from aws_watchdog.utils import current_user_is_root


logger = logging.getLogger('aws_watchdogd')


LOG_FILE = '/var/log/aws_watchdog/aws_watchdog.log'
LOG_LEVEL = logging.INFO
LOG_FORMAT = '%(asctime)s %(levelname)s %(message)s'

LOG_DIR = os.path.dirname(LOG_FILE)
os.makedirs(LOG_DIR, exist_ok=True)


logging.basicConfig(
    level=LOG_LEVEL,
    format=LOG_FORMAT,
    handlers=[
        TimedRotatingFileHandler(
            LOG_FILE,
            when='h',
            interval=24,
            backupCount=5,
        ),
    ],
)


@click.command()
@click.option(
    '--config-id',
    default=1,
    help='ID of config entry in DynamoDB (default is 1)',
)
def aws_watchdog_daemon(config_id):

    daemon_context = daemon.DaemonContext(
        pidfile=lockfile.FileLock('/var/run/aws_watchdogd.pid'),
        files_preserve=[
            *[handler.stream for handler in logging.root.handlers]
        ],
    )

    with daemon_context:
        logger.info('Starting AWS watchdog daemon')

        if current_user_is_root():
            logger.warn('Running things as root can be dangerous !!')

        aws_watchdog(config_id)


if __name__ == '__main__':
    aws_watchdog_daemon()
