#!/usr/bin/env python3
import logging
import logging.config
import os
from logging.handlers import TimedRotatingFileHandler

from aws_watchdog import aws_watchdog_daemon


logger = logging.getLogger('aws_watchdogd')


LOG_FILE = '/var/log/aws_watchdog/aws_watchdog.log'
LOG_LEVEL = logging.INFO
LOG_FORMAT = '%(asctime)s %(levelname)s %(message)s'

LOG_DIR = os.path.dirname(LOG_FILE)
os.makedirs(LOG_DIR, exist_ok=True)


logging.basicConfig(
    level=LOG_LEVEL,
    format=LOG_FORMAT,
    handlers=[
        TimedRotatingFileHandler(
            LOG_FILE,
            when='h',
            interval=24,
            backupCount=5,
        ),
    ],
)

aws_watchdog_daemon()
